export default {
  SYMBOL: $ => choice("#", "@"),
  SEMICOLON: $ => ";",
  RPAREN: $ => ")",
  LPAREN: $ => "(",
  NEWLINE: $ => "\n",
  CONST: $ => choice(new RustRegex('"[^"]*"'), new RustRegex("-?(0[bx])?[0-9]+")),
  IDENTIFIER: $ => new RustRegex('[a-z_][a-z0-9_]*'),
  OPERATOR: $ => choice(">>>", "<<=", ">>=", "===", "==", "!=", "<=", ">=", "&&", "||", "<<", ">>", "+=", "-=", "*=", "/=", "%=", "&=", "|=", "^=", "::", "->", "+", "-", "*", "/", "%", "=", "<", ">", "!", "&", "|", "^", "~", "?"),
  COLON: $ => ":",
  RBRACE: $ => "}",
  LBRACE: $ => "{",
  RBRACKET: $ => "]",
  LBRACKET: $ => "[",
  COMMA: $ => ",",
  DOT: $ => ",",
  comment: ($) => token(prec(200, seq("//", /.*/))),
};